definitions:
  avator.AvatorResponse:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  favorites_s.RequestBody:
    properties:
      id:
        type: integer
      url:
        type: string
    type: object
  generate_s.ImageParaments:
    properties:
      height:
        maximum: 1024
        minimum: 128
        type: integer
      prompt:
        type: string
      sampling_method:
        enum:
        - DDIM
        - PLMS
        - K-LMS
        type: string
      seed:
        type: string
      steps:
        maximum: 100
        minimum: 1
        type: integer
      width:
        maximum: 1024
        minimum: 128
        type: integer
    required:
    - height
    - prompt
    - sampling_method
    - seed
    - steps
    - width
    type: object
  like.ReqBody:
    properties:
      url:
        type: string
    type: object
  user.UserInformation:
    properties:
      avatar_url:
        type: string
      create_time:
        type: string
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      score:
        type: integer
      token:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/addFavoritedImage:
    post:
      consumes:
      - application/json
      description: 根据图像URL或ID收藏图像
      parameters:
      - description: 请求体
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/favorites_s.RequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: 图像收藏成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 无效的请求格式
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 未找到用户信息
          schema:
            additionalProperties: true
            type: object
        "404":
          description: 未找到对应的图像
          schema:
            additionalProperties: true
            type: object
        "409":
          description: 该图像已经被收藏过
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 检查收藏状态失败
          schema:
            additionalProperties: true
            type: object
      summary: 收藏图像
      tags:
      - favorites
  /auth/deleteFavoritedImage:
    delete:
      consumes:
      - application/json
      description: 根据图像URL或ID取消收藏图像
      parameters:
      - description: 图像URL
        in: query
        name: url
        type: string
      - description: 图像ID
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 取消图像收藏成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 无效的请求格式
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 未找到用户信息
          schema:
            additionalProperties: true
            type: object
        "404":
          description: 未找到对应的图像
          schema:
            additionalProperties: true
            type: object
        "409":
          description: 该图像未被收藏过，不可取消收藏
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 检查收藏状态失败
          schema:
            additionalProperties: true
            type: object
      summary: 取消图像收藏
      tags:
      - favorites
  /auth/generate:
    post:
      consumes:
      - application/json
      description: 根据传入的参数生成图片并返回图片的URL
      parameters:
      - description: 图片参数
        in: body
        name: imageParaments
        required: true
        schema:
          $ref: '#/definitions/generate_s.ImageParaments'
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 参数错误
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 内部错误
          schema:
            additionalProperties: true
            type: object
      summary: 生成图片
      tags:
      - 图片生成
  /auth/getavator:
    get:
      consumes:
      - application/json
      description: 获取用户头像接口
      produces:
      - application/json
      responses:
        "200":
          description: 获取头像成功
          schema:
            $ref: '#/definitions/avator.AvatorResponse'
        "401":
          description: 名字解析出错
          schema:
            $ref: '#/definitions/avator.AvatorResponse'
        "500":
          description: 查询头像失败
          schema:
            $ref: '#/definitions/avator.AvatorResponse'
      summary: 获取用户头像
      tags:
      - user
  /auth/like:
    put:
      consumes:
      - application/json
      description: 点赞图片接口
      parameters:
      - description: 图片 URL
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/like.ReqBody'
      produces:
      - application/json
      responses:
        "200":
          description: 点赞成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 缺少图片 URL
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 名字解析出错
          schema:
            additionalProperties: true
            type: object
        "409":
          description: 用户已点赞该图片
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 数据库操作错误
          schema:
            additionalProperties: true
            type: object
      summary: 点赞图片
      tags:
      - image
  /auth/setavator:
    post:
      consumes:
      - application/json
      description: 设置用户头像接口
      parameters:
      - description: 头像 URL
        in: body
        name: url
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 头像更新成功
          schema:
            $ref: '#/definitions/avator.AvatorResponse'
        "401":
          description: 名字解析出错
          schema:
            $ref: '#/definitions/avator.AvatorResponse'
        "500":
          description: 更新头像失败
          schema:
            $ref: '#/definitions/avator.AvatorResponse'
      summary: 设置用户头像
      tags:
      - user
  /auth/user/favoritedimages:
    get:
      description: 获取当前用户收藏的所有图像
      produces:
      - application/json
      responses:
        "200":
          description: 获取用户收藏的图像成功
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 未找到用户信息
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 查询用户收藏的图片失败
          schema:
            additionalProperties: true
            type: object
      summary: 获取当前登录用户的收藏图像
      tags:
      - favorites
  /auth/user/images:
    get:
      description: 获取当前用户生成的所有图像
      produces:
      - application/json
      responses:
        "200":
          description: 获取用户的图像成功
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 未找到用户信息
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 查询用户图片失败
          schema:
            additionalProperties: true
            type: object
      summary: 获取当前登录用户生成的图像
      tags:
      - images
  /auth/user/images/timeRange:
    get:
      description: 获取当前用户在指定时间范围内生成的图像列表
      parameters:
      - description: '开始时间 (格式: YYYY-MM-DD 或 YYYY-MM-DDTHH:MM:SSZ)'
        in: query
        name: start_time
        required: true
        type: string
      - description: '结束时间 (格式: YYYY-MM-DD 或 YYYY-MM-DDTHH:MM:SSZ)'
        in: query
        name: end_time
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 查询图像列表成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 无效的开始或结束时间格式
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 未找到用户信息
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 查询图像列表失败
          schema:
            additionalProperties: true
            type: object
      summary: 查询用户在指定时间段内生成的所有图像
      tags:
      - images
  /auth/user/info:
    get:
      consumes:
      - application/json
      description: 根据用户名、邮箱或用户ID获取用户信息
      parameters:
      - description: 用户名
        in: query
        name: username
        type: string
      - description: 邮箱
        in: query
        name: email
        type: string
      - description: 用户ID
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 获取用户信息成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 无效的请求数据
          schema:
            additionalProperties: true
            type: object
        "404":
          description: 用户未找到
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 查询失败
          schema:
            additionalProperties: true
            type: object
      summary: 获取用户信息
      tags:
      - user
  /auth/user/update:
    put:
      consumes:
      - application/json
      description: 更新用户的详细信息（不能更新用户名）
      parameters:
      - description: 用户信息更新数据
        in: body
        name: requestBody
        required: true
        schema:
          additionalProperties: true
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: 用户信息更新成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 请求数据格式错误
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 未找到用户信息
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 更新用户信息失败
          schema:
            additionalProperties: true
            type: object
      summary: 更新用户信息
      tags:
      - users
  /image:
    get:
      description: 根据图像的 URL、用户名或 ID 查询某张图像
      parameters:
      - description: 图像的URL
        in: query
        name: url
        type: string
      - description: 用户名
        in: query
        name: username
        type: string
      - description: 图像ID
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 查询图像成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 无效的图像ID或用户名
          schema:
            additionalProperties: true
            type: object
        "404":
          description: 未找到相关图片
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 查询用户的图片失败
          schema:
            additionalProperties: true
            type: object
      summary: 查询指定图像
      tags:
      - images
  /image/all:
    get:
      consumes:
      - application/json
      description: 获取系统中所有图像的信息
      produces:
      - application/json
      responses:
        "200":
          description: 获取图像列表成功
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 获取图像列表失败
          schema:
            additionalProperties: true
            type: object
      summary: 获取所有图像信息
      tags:
      - images
  /images/findByFeature:
    get:
      consumes:
      - application/json
      description: 根据提供的特征列表查找图片
      parameters:
      - collectionFormat: csv
        description: 特征列表
        in: query
        items:
          type: string
        name: feature
        required: true
        type: array
      - description: 是否只查找自己的图片
        in: query
        name: isOwn
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功查找图片
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 请求错误
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 未授权
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 内部服务器错误
          schema:
            additionalProperties: true
            type: object
      summary: 根据特征查找图片
      tags:
      - 图片管理
  /login:
    post:
      consumes:
      - application/json
      description: 用户登录接口
      parameters:
      - description: 用户名和密码
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.UserInformation'
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 请求数据格式错误
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 用户不存在或密码错误
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 生成 token 错误
          schema:
            additionalProperties: true
            type: object
      summary: 用户登录
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      description: 用户注册接口
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.UserInformation'
      produces:
      - application/json
      responses:
        "200":
          description: 注册成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 请求数据格式错误
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 用户创建失败
          schema:
            additionalProperties: true
            type: object
      summary: 用户注册
      tags:
      - auth
  /user/all:
    get:
      description: 获取系统中所有用户的列表
      produces:
      - application/json
      responses:
        "200":
          description: 获取用户列表成功
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 获取用户列表失败
          schema:
            additionalProperties: true
            type: object
      summary: 获取所有用户信息
      tags:
      - users
  /users:
    delete:
      consumes:
      - application/json
      description: 根据用户名删除用户，只有root用户才能删除其他用户
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功删除用户
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 请求错误
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 未授权
          schema:
            additionalProperties: true
            type: object
        "404":
          description: 用户不存在
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 内部服务器错误
          schema:
            additionalProperties: true
            type: object
      summary: 删除用户
      tags:
      - 用户管理
swagger: "2.0"
